// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiFmDnxmO3EUGSvPg6E0c_ChQ44BKSXsc',
    appId: '1:288329164276:android:d96d9f533918dfbc48c5a1',
    messagingSenderId: '288329164276',
    projectId: 'whatsapp-messenger-clone-53c59',
    storageBucket: 'whatsapp-messenger-clone-53c59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr3WFBD4D7g9mUTcG5Sc8BO_emLGln8qs',
    appId: '1:288329164276:ios:a86b1a50d56279ba48c5a1',
    messagingSenderId: '288329164276',
    projectId: 'whatsapp-messenger-clone-53c59',
    storageBucket: 'whatsapp-messenger-clone-53c59.appspot.com',
    iosClientId: '288329164276-8bdbsf3mjb483tl3b3521dcc4780g8ic.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappMessenger',
  );
}
